from selenium import webdriver
import time

driver = webdriver.Chrome()
faucetpay_address = "your_address"

driver.get("https://efaucet.eu/index.php")
print("loading page...")
time.sleep(10)
driver.find_element_by_name("wantusername").click()
driver.switch_to.window(driver.window_handles[0])
driver.close()
driver.switch_to.window(driver.window_handles[0])
driver.find_element_by_name("wantusername").send_keys(faucetpay_address)
time.sleep(11)
driver.find_element_by_css_selector(".btn.btn-brand-02.bd-0.mg-l-5.pd-sm-x-25").click()
print("1")
time.sleep(14)
driver.find_element_by_css_selector(".btn.btn-brand-02.bd-0.mg-l-5.pd-sm-x-25").click()
print("2")
time.sleep(15)
driver.find_element_by_id("s11proceed").click()
print("3")
time.sleep(16)
driver.find_element_by_id("s21proceed").click()
print("4")
time.sleep(14)
driver.find_element_by_css_selector(".g-recaptcha.btn.btn-brand-02.bd-0.mg-l-5.pd-sm-x-25").click()
driver.switch_to.window(driver.window_handles[0])
driver.close()
driver.switch_to.window(driver.window_handles[0])
time.sleep(22)
driver.find_element_by_css_selector(".g-recaptcha.btn.btn-brand-02.bd-0.mg-l-5.pd-sm-x-25").click()
print("1- Try solve the captchar")
time.sleep(40)
print("2- Try solve by audio")